- name: Demo on printing
  hosts: localhost
  tasks:
    - name: print hello world
      ansible.builtin.debug:
        msg:Hello printing

- name: Demo on variables
  hosts: localhost
  var:
    URL: example.com
  tasks:
    - name: print variables
      ansible.builtin.debug:
        msg:"{{ URL }}"
