- name: Demo on printing
  hosts: localhost
  tasks:
     - name: print hello world
       ansible.builtin.debug:
         msg:Hello printing

- name: Demo on variables
  hosts: localhost
  vars:
    URL: example.com
  tasks:
     - name: print variables
       ansible.builtin.debug:
         msg:"{{ URL }}"
#hhjhjjh
#hjhjhj
- name: Demo on task level var
  hosts: localhost
  tasks:
     - name: print a variable
       ansible.builtin.debug:
         msg:"{{ URL }}"
       var:
          URL: example.com
