- name: print used memory
  hosts: localhost
  tasks:
  - name: Get memory
    ansible.builtin.shell: free | grep Mem |xargs
    register: free

#  - name: set_fact
#    ansible.builtin.set_fact:
#     free: "{{free.stdout | split(' ')}}"

  - name: print free variables
    ansible.builtin.debug:
      msg: "{{free}}"



