- name: print used memory
  hosts: localhost
  tasks:
  - name: Get memory
    ansible.builtin.shell: free | grep Mem |xargs
    register: free

  - name: print free variables
    ansible.builtin.debug:
      msg: "{{free}}"




  - name: set_fact
    ansible.builtin.set_fact:
     free: "{{free.stdout | split(' ')}}"

  - name: print free variables
    ansible.builtin.debug:
      total: "{{free[1]}}"
      free: "{{free[2]}}"

  - name: print free output
    ansible.builtin.debug:
      msg: "{{free|int / total|int}}"






